<Project>
    <PropertyGroup>
        <TSName>Simple_Progression</TSName>
        <TSAuthor>AuriRex</TSAuthor>
        <TSVersion>2025.1.0</TSVersion> <!-- TSVersion empty = GitInfo used instead (if available; check nuget) -->
        <TSWebsite>https://github.com/AuriRex/GTFO_SimpleProgression</TSWebsite>
        <TSDescription>A LocalProgression implementation, including local vanity item and booster drops.</TSDescription>
    </PropertyGroup>
    <ItemGroup>
        <!-- Add the Dependency strings here, one for each dependency -->
        <TSDependencyStrings Include="BepInEx-BepInExPack_GTFO-3.2.2" InProject="false" />
        <TSDependencyStrings Include="AuriRex-Clonesoft_Json-13.0.0" InProject="false" />
        <!-- <TSDependencyStrings Include="Some-Other-Dependency-1.2.3" InProject="false" /> -->
    </ItemGroup>
</Project>